apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: my-java-app
  namespace: philippenunes-dev
  labels:
    app: my-java-app
    component: build
spec:
  completionDeadlineSeconds: 1200
  failedBuildsHistoryLimit: 5
  successfulBuildsHistoryLimit: 5
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://github.com/philippenunes/java-demo-openshift
      ref: main
    contextDir: .
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: java:openjdk-17-ubi8
        namespace: openshift
      env:
        - name: MAVEN_ARGS
          value: "clean package -DskipTests"
        - name: JAVA_HOME
          value: "/usr/lib/jvm/java-17-openjdk"
  output:
    to:
      kind: ImageStreamTag
      name: my-java-app:latest
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: java:openjdk-17-ubi8
          namespace: openshift