apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  # 🔧 RECURSOS REDUZIDOS PARA CRC
  controller:
    resources:
      requests:
        cpu: "100m"
        memory: "512Mi" 
      limits:
        cpu: "1"
        memory: "1Gi"
  
  server:
    route:
      enabled: true
    service:
      type: ''
  
  # 🛡️ RBAC PARA SYSTEM ADMINS
  rbac:
    defaultPolicy: ''
    policy: |
      g, system:cluster-admins, role:admin
      g, cluster-admins, role:admin
    scopes: '[groups]'
  
  # 🎯 INTEGRAÇÃO COM OPENSHIFT OAUTH
  sso:
    provider: dex
    dex:
      openShiftOAuth: true