apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-java-app-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/philippenunes/java-demo-openshift'
    targetRevision: main  
    path: k8s/dev

  destination:
    server: 'https://192.168.1.3:6443'
    namespace: philippenunes-dev

  # Configuração para evitar problemas de discovery
  ignoreDifferences:
  - group: "*"
    kind: "*"
    managedFieldsManagers:
    - kube-controller-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true