apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-java-app-build
  namespace: openshift-gitops
spec:
  project: default

  source:
    repoURL: 'https://github.com/philippenunes/java-demo-openshift'
    targetRevision: main  
    path: k8s/overlays/dev-build  # ← Usando overlay dev-build
    kustomize: {}

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: philippenunes-dev

  # Configuração para evitar problemas de discovery
  ignoreDifferences:
  - group: "*"
    kind: "*"
    managedFieldsManagers:
    - kube-controller-manager

  syncPolicy:
    # ✅ AutoSync habilitado 
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true