apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-java-app-dev
  namespace: argocd
  # 🎯 CONFIGURAÇÃO PARA ARGOCD IMAGE UPDATER
  annotations:
    argocd-image-updater.argoproj.io/image-list: my-java-app=image-registry.openshift-image-registry.svc:5000/philippenunes-dev/my-java-app
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default

  source:
    repoURL: 'https://github.com/philippenunes/java-demo-openshift'
    targetRevision: main  
    path: k8s/overlays/dev  # 🎯 Nova estrutura Kustomize

  destination:
    server: 'https://192.168.1.3:6443'
    namespace: philippenunes-dev

  # Configuração para evitar problemas de discovery
  ignoreDifferences:
  - group: "*"
    kind: "*"
    managedFieldsManagers:
    - kube-controller-manager

  syncPolicy:
    # ✅ AutoSync habilitado para desenvolvimento
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true