# 🎯 APLICAÇÃO ARGOCD SIMPLES PARA TESTE GITOPS
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-java-app-dev
  namespace: openshift-gitops
  annotations:
    # 🤖 CONFIGURAÇÕES PARA ARGOCD IMAGE UPDATER
    argocd-image-updater.argoproj.io/image-list: my-java-app=image-registry.openshift-image-registry.svc:5000/philippenunes-dev/my-java-app:dev
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/my-java-app.update-strategy: digest
spec:
  project: default
  
  source:
    repoURL: 'https://github.com/philippenunes/java-demo-openshift'
    targetRevision: main  
    path: k8s/overlays/dev
    
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: philippenunes-dev
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true