# 🏗️ Build para GitOps com Image Updater
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: my-java-app
  namespace: philippenunes-prod
  labels:
    app: my-java-app
spec:
  lookupPolicy:
    local: false

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: my-java-app
  namespace: philippenunes-dev
  labels:
    app: my-java-app
spec:
  lookupPolicy:
    local: false

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: my-java-app
  namespace: philippenunes-dev
  labels:
    app: my-java-app
spec:
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'java:openjdk-17-ubi8'
      env:
      - name: MAVEN_ARGS
        value: clean package -DskipTests
  source:
    type: Git
    git:
      uri: 'https://github.com/philippenunes/java-demo-openshift'
      ref: develop
    contextDir: .
  output:
    to:
      kind: ImageStreamTag
      name: 'my-java-app:latest'
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChange:
      from:
        kind: ImageStreamTag
        name: java:openjdk-17-ubi8
        namespace: openshift
  runPolicy: Serial
  completionDeadlineSeconds: 1200
